-- 1: backup round table
DROP TABLE IF EXISTS ROUND_BACKUP;
CREATE TABLE ROUND_BACKUP LIKE ROUND;
INSERT ROUND_BACKUP SELECT * FROM ROUND;
-- 2: add column and reference constraint
ALTER TABLE ROUND ADD COLUMN LEAGUE_ID INT NOT NULL;
ALTER TABLE ROUND ADD CONSTRAINT foreign_key_LEAGUE_ID FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE(LEAGUE_ID);
UPDATE ROUND SET ROUND.LEAGUE_ID = (SELECT DIVISION.LEAGUE_ID FROM DIVISION WHERE DIVISION.DIVISION_ID = ROUND.DIVISION_ID);
-- 3: copy new ROUND data to temp table
DROP TABLE IF EXISTS ROUND_NEW;
CREATE TABLE ROUND_NEW LIKE ROUND;
ALTER TABLE ROUND_NEW ADD CONSTRAINT foreign_key_LEAGUE_ID FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE(LEAGUE_ID) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ROUND_NEW ADD CONSTRAINT unique_LEAGUE_ID_START UNIQUE (LEAGUE_ID, START);
ALTER TABLE ROUND_NEW DROP INDEX unique_DIVISION_ID_START;
ALTER TABLE ROUND_NEW DROP COLUMN DIVISION_ID;
INSERT ROUND_NEW (START,END,LEAGUE_ID) SELECT START,END,LEAGUE_ID from ROUND GROUP BY START,END,LEAGUE_ID ORDER BY START,LEAGUE_ID,END;
-- 4: backup matches table
DROP TABLE IF EXISTS MATCHES_BACKUP;
CREATE TABLE MATCHES_BACKUP LIKE MATCHES;
INSERT MATCHES_BACKUP SELECT * FROM MATCHES;
-- 5: map old id to new id
ALTER TABLE MATCHES DROP INDEX unique_PLAYER_ONE_ID_PLAYER_TWO_ID_ROUND_ID;
ALTER TABLE MATCHES ADD CONSTRAINT unique_PLAYER_ONE_ID_PLAYER_TWO_ID_ROUND_ID_DIVISION_ID UNIQUE (PLAYER_ONE_ID, PLAYER_TWO_ID, ROUND_ID, DIVISION_ID);
UPDATE MATCHES SET MATCHES.ROUND_ID = (SELECT ROUND_NEW.ROUND_ID FROM ROUND_NEW JOIN ROUND ON ROUND_NEW.START = ROUND.START AND ROUND_NEW.LEAGUE_ID = ROUND.LEAGUE_ID WHERE MATCHES.ROUND_ID = ROUND.ROUND_ID);
-- 6: update ROUND table
DELETE FROM ROUND;
ALTER TABLE ROUND_NEW ADD CONSTRAINT foreign_key_LEAGUE_ID FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE(LEAGUE_ID) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ROUND ADD CONSTRAINT unique_LEAGUE_ID_START UNIQUE (LEAGUE_ID, START);
ALTER TABLE ROUND DROP INDEX unique_DIVISION_ID_START;
ALTER TABLE ROUND DROP COLUMN DIVISION_ID;
INSERT ROUND SELECT * FROM ROUND_NEW;
DROP TABLE IF EXISTS ROUND_NEW;
